### ISSUE TITLE
不断 captcha needed

### ISSUE THREAD

**Issue by nuomi1** [ly0/web.baidupan#1]
captcha > 输入 img42.com 看到的字符，然后回车，却不断 captcha needed。

**Comment by ly0** [comment]
诶？我这里测试是正常的呢，新装的baidupcsapi和web.baidupan 看看用户密码设置对了么？

**Comment by nuomi1** [comment]
貌似我的操作有问题？
——————————
首先 `pip2 install baidupcsapi web.py`，然后 `python2 launcher.py`。
接着就是上述情况。

**Comment by ly0** [comment]
暂时不要使用pip安装baidupcsapi，pypi上的版本可能不是最新的，http://github.com/ly0/baidupcsapi 试试卸载baidupcsapi库后从这里安装。pypi上的一会我更新一下。

需要修改launcher.py里的账号密码哦

**Comment by nuomi1** [comment]
README.md 里没有写，以为是启动了再打账号密码……

**Comment by ly0** [comment]
> <我错了 我现在加上去
