### ISSUE TITLE
目前默认是从根目录开始显示，能不能指定一个目录？

### ISSUE THREAD

**Issue by ouewqa** [ly0/web.baidupan#2]
比如我想从 /apps/abc 下开始显示
其他目录我又不想显示怎么处理？

**Comment by ouewqa** [comment]
还有就是默认是8080端口，这个在哪里修改呀？

**Comment by ly0** [comment]
json.loads(pcs.list_files('/').content

/改成 /apps/abc即可

**Comment by ly0** [comment]
app.run() 改成 app.run('0.0.0.0:80')
